### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by nickveenhof**
Allowing local files to be read

### CODE REVIEW

**Comment by nickveenhof** [comment]
Ping @br-adam-newman , can you take a look? We're using this currently heavily so that it allows us to pull in local files as reference. not all json schemas are publically available obviously :). The spec also allows the use of local files.

**Comment by br-adam-newman** [comment]
Spam filter caught the first email. I'll tweak this a little bit and publish an update to the node repository. Then I'll add a whitelist rule to spam filter.

**Comment by nickveenhof** [comment]
With this, your documentation is also outdated that it HAS to be hosted. Now you can easily run this on your local computer or eg, in travis to generate the json schema documentation using raml2html for example.

**Comment by br-adam-newman** [comment]
Published a revised version to npm as 1.1.0

**Pull request merged**
